### ISSUE TITLE
Need to change the parameters with wrong names

### ISSUE THREAD

**Issue by rjshim** [YDLIDAR/ydlidar_ros2_driver#1]
Hi,

As the title says, in the yaml file in the location "ydlidar_ros2_driver/params/ydlidar.yaml", param names have to be fixed as below.

max_range -> range_max
min_range -> range_min

Ryan

**Comment by yangfuyuan** [comment]
It's fixed. Thanks.

**Comment by rjshim** [comment]
Thanks for the prompt support!
